### ISSUE TITLE
Make the IGVC rover look better

### ISSUE THREAD

**Issue by daweim0** [RockRaidersInc/Mechanical#63]
Wiring needs to be cleaned up at the very least.

**Comment by J-Corbin** [comment]
no

**Comment by daweim0** [comment]
So hear me out, the IGVC rover is what we'll be showing to recruits and sponsors until the URC rover is done. It will be the public face of our club. We should make it look a little professional.

**Comment by cmcgowan27** [comment]
no

**Comment by J-Corbin** [comment]
yeah we can look into it. I won't have time
