### ISSUE TITLE
Determine torque required for wrist

### ISSUE THREAD

**Issue by cmcgowan27** [RockRaidersInc/Mechanical#65]
Needed to figure out current draw for arm

**Comment by daweim0** [comment]
Assigning to Jack. We determined 10 newton-meters last semester, I don't know if that's still accurate.

**Comment by J-Corbin** [comment]
There's 3 motors in the wrist. I'm going to need a little more direction than just "Torque required". Torque required total? Torque required for the first roll rotation? Torque required for the pitch/roll rotation? Torque per motor? Before or after gearbox?

**Comment by J-Corbin** [comment]
Also, assigning to Sam since the wrist/end effector is going to be his baby now.
